### ISSUE TITLE
Runtime error on Fedora 33

### ISSUE THREAD

**Issue by kushaldas** [SaptakS/saikoro#1]
I am trying to execute from git repo on Fedora 33.

```
saikoro on  main via 🐍 v3.9.2 (.venv)took 22s 
✦ ❯ ./run.py 
Traceback (most recent call last):
  File "/home/kdas/code/saikoro/./run.py", line 2, in <module>
    import saikorosrc
  File "/home/kdas/code/saikoro/saikorosrc/__init__.py", line 3, in <module>
    from PySide6 import QtCore, QtWidgets, QtGui
ImportError: libOpenGL.so.0: cannot open shared object file: No such file or directory

```

**Comment by ravish0007** [comment]
I had the same issue, I installed freeglut and freeglut-devel in order to make it work.

`sudo dnf install freeglut freeglut-devel`
